from typing import Dict


class TexChar:
    def __init__(self, cmd, char, unicode):
        self.command = cmd
        self.char = char
        self.unicode = unicode


class TexCharSet:
    def __init__(self):
        self.charset = {}  # type: Dict[str, TexChar]

    def add(self, cmd, char, unicode):
        self.charset[cmd] = TexChar(cmd, char, unicode)

    def get_char(self, cmd):
        if cmd in self.charset:
            return self.charset[cmd].char
        return None


TEX_CHARSET = TexCharSet()

# Escape character
TEX_CHARSET.add('{', '{', 123)
TEX_CHARSET.add('}', '}', 125)

# Greek small letter
TEX_CHARSET.add('alpha', 'α', 945)
TEX_CHARSET.add('beta', 'β', 946)
TEX_CHARSET.add('gamma', 'γ', 947)
TEX_CHARSET.add('delta', 'δ', 948)
TEX_CHARSET.add('epsilon', 'ε', 949)
TEX_CHARSET.add('zeta', 'ζ', 950)
TEX_CHARSET.add('eta', 'η', 951)
TEX_CHARSET.add('theta', 'θ', 952)
TEX_CHARSET.add('iota', 'ι', 953)
TEX_CHARSET.add('kappa', 'κ', 954)
TEX_CHARSET.add('lamda', 'λ', 955)
TEX_CHARSET.add('mu', 'μ', 956)
TEX_CHARSET.add('nu', 'ν', 957)
TEX_CHARSET.add('xi', 'ξ', 958)
TEX_CHARSET.add('omicron', 'ο', 959)
TEX_CHARSET.add('pi', 'π', 960)
TEX_CHARSET.add('rho', 'ρ', 961)
TEX_CHARSET.add('sigma', 'σ', 963)
TEX_CHARSET.add('tau', 'τ', 964)
TEX_CHARSET.add('upsilon', 'υ', 965)
TEX_CHARSET.add('phi', 'φ', 966)
TEX_CHARSET.add('chi', 'χ', 967)
TEX_CHARSET.add('psi', 'ψ', 968)
TEX_CHARSET.add('omega', 'ω', 969)

# Greek capital letter
TEX_CHARSET.add('Alpha', 'Α', 913)
TEX_CHARSET.add('Beta', 'Β', 914)
TEX_CHARSET.add('Gamma', 'Γ', 915)
TEX_CHARSET.add('Delta', 'Δ', 916)
TEX_CHARSET.add('Epsilon', 'Ε', 917)
TEX_CHARSET.add('Zeta', 'Ζ', 918)
TEX_CHARSET.add('Eta', 'Η', 919)
TEX_CHARSET.add('Theta', 'Θ', 920)
TEX_CHARSET.add('Iota', 'Ι', 921)
TEX_CHARSET.add('Kappa', 'Κ', 922)
TEX_CHARSET.add('Lamda', 'Λ', 923)
TEX_CHARSET.add('Mu', 'Μ', 924)
TEX_CHARSET.add('Nu', 'Ν', 925)
TEX_CHARSET.add('Xi', 'Ξ', 926)
TEX_CHARSET.add('Omicron', 'Ο', 927)
TEX_CHARSET.add('Pi', 'Π', 928)
TEX_CHARSET.add('Rho', 'Ρ', 929)
TEX_CHARSET.add('Sigma', 'Σ', 931)
TEX_CHARSET.add('Tau', 'Τ', 932)
TEX_CHARSET.add('Upsilon', 'Υ', 933)
TEX_CHARSET.add('Phi', 'Φ', 934)
TEX_CHARSET.add('Chi', 'Χ', 935)
TEX_CHARSET.add('Psi', 'Ψ', 936)
TEX_CHARSET.add('Omega', 'Ω', 937)

# Greek letter variant
TEX_CHARSET.add('varsigma', 'ς', 962)
TEX_CHARSET.add('varbeta', 'ϐ', 976)
TEX_CHARSET.add('vartheta', 'ϑ', 977)
TEX_CHARSET.add('varphi', 'ϕ', 981)
TEX_CHARSET.add('varpi', 'ϖ', 982)
TEX_CHARSET.add('stigma', 'Ϛ', 986)
TEX_CHARSET.add('digamma', 'Ϝ', 988)
TEX_CHARSET.add('koppa', 'Ϟ', 990)
TEX_CHARSET.add('sampi', 'Ϡ', 992)
TEX_CHARSET.add('varkappa', 'ϰ', 1008)
TEX_CHARSET.add('varrho', 'ϱ', 1009)
TEX_CHARSET.add('lunatesigma', 'ϲ', 1010)

# Symbols
TEX_CHARSET.add('dagger', '†', 8224)
TEX_CHARSET.add('ddagger', '‡', 8225)
TEX_CHARSET.add('bullet', '•', 8226)
TEX_CHARSET.add('dot', '․', 8228)
TEX_CHARSET.add('ddot', '‥', 8229)
TEX_CHARSET.add('dots', '…', 8230)
TEX_CHARSET.add('cdot', '‧', 8231)
TEX_CHARSET.add('prime', '′', 8242)
TEX_CHARSET.add('scruple', '℈', 8456)
TEX_CHARSET.add('hbar', 'ℏ', 8463)
TEX_CHARSET.add('Im', 'ℑ', 8465)
TEX_CHARSET.add('ell', 'ℓ', 8467)
TEX_CHARSET.add('Re', 'ℜ', 8476)
TEX_CHARSET.add('ohm', 'Ω', 8486)
TEX_CHARSET.add('mho', '℧', 8487)
TEX_CHARSET.add('alef', 'ℵ', 8501)

# Arrows
TEX_CHARSET.add('gets', '←', 8592)
TEX_CHARSET.add('leftarrow', '←', 8592)
TEX_CHARSET.add('uparrow', '↑', 8593)
TEX_CHARSET.add('to', '→', 8594)
TEX_CHARSET.add('rightarrow', '→', 8594)
TEX_CHARSET.add('downarrow', '↓', 8595)
TEX_CHARSET.add('leftrightarrow', '↔', 8596)
TEX_CHARSET.add('updownarrow', '↕', 8597)
TEX_CHARSET.add('nwarrow', '↖', 8598)
TEX_CHARSET.add('nearrow', '↗', 8599)
TEX_CHARSET.add('searrow', '↘', 8600)
TEX_CHARSET.add('swarrow', '↙', 8601)
TEX_CHARSET.add('leadsto', '↝', 8605)
TEX_CHARSET.add('hookleftarrow', '↩', 8617)
TEX_CHARSET.add('hookrightarrow', '↪', 8618)
TEX_CHARSET.add('leftharpoonup', '↼', 8636)
TEX_CHARSET.add('leftharpoondown', '↽', 8637)
TEX_CHARSET.add('upharpoonright', '↾', 8638)
TEX_CHARSET.add('upharpoonleft', '↿', 8639)
TEX_CHARSET.add('rightharpoonup', '⇀', 8640)
TEX_CHARSET.add('rightharpoondown', '⇁', 8641)
TEX_CHARSET.add('downharpoonright', '⇂', 8642)
TEX_CHARSET.add('downharpoonleft', '⇃', 8643)
TEX_CHARSET.add('leftrightharpoons', '⇋', 8651)
TEX_CHARSET.add('rightleftharpoons', '⇌', 8652)
TEX_CHARSET.add('Leftarrow', '⇐', 8656)
TEX_CHARSET.add('Uparrow', '⇑', 8657)
TEX_CHARSET.add('Rightarrow', '⇒', 8658)
TEX_CHARSET.add('Downarrow', '⇓', 8659)
TEX_CHARSET.add('Leftrightarrow', '⇔', 8660)
TEX_CHARSET.add('Updownarrow', '⇕', 8661)

# Symbols
TEX_CHARSET.add('forall', '∀', 8704)
TEX_CHARSET.add('complement', '∁', 8705)
TEX_CHARSET.add('partial', '∂', 8706)
TEX_CHARSET.add('exists', '∃', 8707)
TEX_CHARSET.add('emptyset', '∅', 8709)
TEX_CHARSET.add('triangle', '∆', 8710)
TEX_CHARSET.add('nabla', '∇', 8711)
TEX_CHARSET.add('in', '∈', 8712)
TEX_CHARSET.add('notin', '∉', 8713)
TEX_CHARSET.add('ni', '∋', 8715)
TEX_CHARSET.add('notowns', '∌', 8716)
TEX_CHARSET.add('blacksquare', '∎', 8718)
TEX_CHARSET.add('prod', '∏', 8719)
TEX_CHARSET.add('coprod', '∐', 8720)
TEX_CHARSET.add('sum', '∑', 8721)
TEX_CHARSET.add('minus', '−', 8722)
TEX_CHARSET.add('mp', '∓', 8723)
TEX_CHARSET.add('dotplus', '∔', 8724)
TEX_CHARSET.add('setminus', '∖', 8726)
TEX_CHARSET.add('ast', '∗', 8727)
TEX_CHARSET.add('circ', '∘', 8728)
TEX_CHARSET.add('propto', '∝', 8733)
TEX_CHARSET.add('infty', '∞', 8734)
TEX_CHARSET.add('angle', '∠', 8736)
TEX_CHARSET.add('measured angle', '∡', 8737)
TEX_CHARSET.add('spherical angle', '∢', 8738)
TEX_CHARSET.add('divides', '∣', 8739)
TEX_CHARSET.add('does not divide', '∤', 8740)
TEX_CHARSET.add('parallel to', '∥', 8741)
TEX_CHARSET.add('not parallel to', '∦', 8742)
TEX_CHARSET.add('logical and', '∧', 8743)
TEX_CHARSET.add('logical or', '∨', 8744)
TEX_CHARSET.add('intersection', '∩', 8745)
TEX_CHARSET.add('union', '∪', 8746)
TEX_CHARSET.add('int', '∫', 8747)
TEX_CHARSET.add('iint', '∬', 8748)
TEX_CHARSET.add('iiint', '∭', 8749)
TEX_CHARSET.add('oint', '∮', 8750)
TEX_CHARSET.add('oiint', '∯', 8751)
TEX_CHARSET.add('oiiint', '∰', 8752)
TEX_CHARSET.add('therefore', '∴', 8756)
TEX_CHARSET.add('because', '∵', 8757)
TEX_CHARSET.add('dotminus', '∸', 8760)
TEX_CHARSET.add('sim', '∼', 8764)
TEX_CHARSET.add('backsim', '∽', 8765)
